<a href="https://colab.research.google.com/github/vrushikesh123/Generative-ai/blob/main/GenAi1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

# Define the actual and predicted values
y_actual = np.array([20, 30, 40, 50, 60])
y_pred = np.array([20.5, 30.3, 40.2, 50.6, 60.7])

# Calculate Mean Absolute Error (MAE)
def mae(y_actual, y_pred):
    return np.mean(np.abs(y_actual - y_pred))

# Calculate Mean Squared Error (MSE)
def mse(y_actual, y_pred):
    return np.mean((y_actual - y_pred) ** 2)

# Calculate Root Mean Squared Error (RMSE)
def rmse(y_actual, y_pred):
    return np.sqrt(mse(y_actual, y_pred))

# Calculate R-squared
def r2_score(y_actual, y_pred):
    y_mean = np.mean(y_actual)
    ss_total = np.sum((y_actual - y_mean) ** 2)
    ss_residual = np.sum((y_actual - y_pred) ** 2)
    return 1 - (ss_residual / ss_total)

# Calculate error metrics
mae_value = mae(y_actual, y_pred)
mse_value = mse(y_actual, y_pred)
rmse_value = rmse(y_actual, y_pred)
r2_value = r2_score(y_actual, y_pred)

# Print the results
print("Mean Absolute Error (MAE):", mae_value)
print("Mean Squared Error (MSE):", mse_value)
print("Root Mean Squared Error (RMSE):", rmse_value)
print("R-squared:", r2_value)

# Compare with library results (using scikit-learn)
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score as r2_sklearn

mae_sklearn = mean_absolute_error(y_actual, y_pred)
mse_sklearn = mean_squared_error(y_actual, y_pred)
rmse_sklearn = np.sqrt(mse_sklearn)
r2_sklearn_value = r2_sklearn(y_actual, y_pred)

print("\nLibrary Results:")
print("Mean Absolute Error (MAE):", mae_sklearn)
print("Mean Squared Error (MSE):", mse_sklearn)
print("Root Mean Squared Error (RMSE):", rmse_sklearn)
print("R-squared:", r2_sklearn_value)

Mean Absolute Error (MAE): 0.4600000000000016
Mean Squared Error (MSE): 0.24600000000000147
Root Mean Squared Error (RMSE): 0.49598387070549127
R-squared: 0.99877

Library Results:
Mean Absolute Error (MAE): 0.4600000000000016
Mean Squared Error (MSE): 0.24600000000000147
Root Mean Squared Error (RMSE): 0.49598387070549127
R-squared: 0.99877


In [3]:
import numpy as np
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

# Define the actual and predicted values
y_actual = np.array([0, 0, 0, 0, 0, 0, 0])
y_pred = np.array([1, 1, 0, 2, 1, 0, 2])

# Calculate accuracy
accuracy = accuracy_score(y_actual, y_pred)

# Calculate precision
precision = precision_score(y_actual, y_pred, average='weighted')

# Calculate recall
recall = recall_score(y_actual, y_pred, average='weighted')

# Calculate F1-score
f1 = f1_score(y_actual, y_pred, average='weighted')

# Calculate confusion matrix
cm = confusion_matrix(y_actual, y_pred)

# Print the results
print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1-score:", f1)
print("Confusion Matrix:\n", cm)

Accuracy: 0.2857142857142857
Precision: 1.0
Recall: 0.2857142857142857
F1-score: 0.44444444444444436
Confusion Matrix:
 [[2 3 2]
 [0 0 0]
 [0 0 0]]


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
